### ISSUE TITLE
Size of the filter when is detached and placed in the card.

### ISSUE THREAD

**Issue by philipbaginski** [rosamarsky/nova-range-filter#3]
Hi!

I'm using this package to detach filters and place them in the card: https://github.com/outl1ne/nova-detached-filters

When Nova Range Filter is placed in the card, the width of the filter is not set up, and there is no method to do it - see picture.

Making longer name of the filter in the resorce file makes filter wilder, but it is not a method to set up width of the filter - see picture.

Any idea how to solve this problem?
![filters - size](https://user-images.githubusercontent.com/59031869/220382631-b5682ac7-336e-4648-92dd-610bbe47b34a.png)
![filters - size set up by making longer filter name in the resource](https://user-images.githubusercontent.com/59031869/220382685-981a1dd7-94a4-41f8-badd-8d58d36344ac.png)

**Comment by rosamarsky** [comment]
Hi Philip!
This question is not for me:) Best asked to Kaspar Rozin (outl1ne member).

But I think I can give advice. He uses the `width` variable as a meta to
give the filter block a class. so you can provide some class to declare the
width of the block, just use the `withMeta()` method with an array
parameter like ['width' => 'w-full'];
Instead of `w-full` you can specify another class like `w-1/2` or `w-1/5`.
There are size classes: https://tailwindcss.com/docs/width Size classes are
there: https://tailwindcss.com/docs/width

RangeFilter::make('Subtotal', 'subtotal', [
    'min' => floor($amountRange->minSubtotal),
    'max' => ceil($amountRange->maxSubtotal),
])->withMeta(['width' => 'w-1/5']),

**Comment by rosamarsky** [comment]
Hi Philip!
This question is not for me:) Best asked to Kaspar Rozin (outl1ne member).

But I think I can give advice.
He uses the `width` variable as a meta to give the filter block a class. So you can provide some class to declare the
width of the block, just use the `withMeta()` method with an array parameter like `['width' => 'w-full']`;

```php
RangeFilter::make('Subtotal', 'subtotal', [
    'min' => floor($amountRange->minSubtotal),
    'max' => ceil($amountRange->maxSubtotal),
])->withMeta(['width' => 'w-1/5']),
```

Instead of `w-full` you can specify another class like `w-1/2` or `w-1/5`.
There are size classes: https://tailwindcss.com/docs/width

**Comment by philipbaginski** [comment]
Thank you for help. w-full works, but most of the classes not. Any idea how to add class into app and if it will work?
